Revert "jQuery, upgrade to 3.4.1, keep 3.2.1 on disk for older third party plugins and disable jquery-migrations while herre."
-- seems to be for later, dashboard dies with "Uncaught TypeError: e.indexOf is not a function .... "

This reverts commit 244b70b77193f9c4d5f2912ca3c3cccf65f49d55.